###

GET http://localhost:3333/projects

###

GET http://localhost:3333/projects/{{project_id}}

###
# @name createProject

POST http://localhost:3333/projects
Content-Type: application/json

{
  "name": "Project 1",
  "description": "Description 1"
}

###

@project_id = {{createProject.response.body.id}}

###
PATCH  http://localhost:3333/projects/{{project_id}}
Content-Type: application/json

{
  "name": "Project 2",
  "description": "Description 2",
  "started_at": "2020-01-01"
}

###
POST  http://localhost:3333/projects/{{project_id}}/start
Content-Type: application/json

{
  "started_at": "2020-01-01"
}